[build]
  # No build process needed - static HTML site
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' data:;"

# Simple redirect for SPA behavior - removed problematic conditions
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for Alpine Surveying website
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"